name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run build
        run: npm publish lib --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
